name:                tsalesman
version:             0.1.0.0
github:              "noahmartinwilliams/tsalesman"
license:             BSD-3-Clause
author:              "Noah Martin Williams"
maintainer:          "noahmartinwilliams@gmail.com"
copyright:           "GPL"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/noahmartinwilliams/tsalesman#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src/
  dependencies:
  - containers 
  - deepseq
  - dijkstra-simple
  - parallel
  - ieee754
  - transformers
  - random
  - memoize
  - mtl

executables:
  tsalesman:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers
    - deepseq
    - dijkstra-simple
    - megaparsec
    - megaparsec-csv
    - megaparsec-dimacs-graph
    - mtl
    - parallel
    - random
    - split
    - tsalesman

tests:
  tsalesman-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tsalesman
